### ISSUE TITLE
Is that my wallpaper?

### ISSUE THREAD

**Issue by frosetrain** [yeyushengfan258/Win11Nord-kde#1]
I think you used my "blobs" wallpaper from Reddit for [1.png](https://github.com/yeyushengfan258/Win11Nord-kde/blob/main/wallpaper/Win11OS-Nord/contents/images/1.png), and put a Windows logo on it to make [2560x1440.png](https://github.com/yeyushengfan258/Win11Nord-kde/blob/main/wallpaper/Win11OS-Nord/contents/images/2560x1440.png) :)

Although this wallpaper isn't actually mine because it is just a re-colored GNOME wallpaper.

But thanks for including this wallpaper in your awesome KDE theme and spreading the wallpaper to many people's desktops!

**Comment by yeyushengfan258** [comment]
I also saw it in other videos by accident, and it feels pretty good wallpaper.
Thank you.
